//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Resim = new HashSet<Resim>();
            this.SatisDetay = new HashSet<SatisDetay>();
            this.UrunOzellik = new HashSet<UrunOzellik>();
        }
    
        public int Id { get; set; }
        [Display(Name="Ürün Adý")]
        public string Adi { get; set; }
        [Display(Name = "Ürün Açýklamasý")]
        public string Aciklama { get; set; }
        [Display(Name = "Ürün Alým Fiyatý")]
        public Nullable<decimal> AlisFiyat { get; set; }
        [Display(Name = "Ürün Satýþ Fiyatý")]
        public Nullable<decimal> SatisFiyat { get; set; }
        [Display(Name = "Ürün Eklenme Tarihi")]
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        [Display(Name = "Son Kullanma Tarihi")]
        public Nullable<System.DateTime> SonKullanmaTarihi { get; set; } 
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> MarkaID { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resim> Resim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisDetay> SatisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunOzellik> UrunOzellik { get; set; }
    }
}
